stages: 
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:  #dependencies
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv

  split_data:
    cmd: python src/splitting_data.py --config=params.yaml
    deps:
    - src/splitting_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_wine_quality.csv

  model_evaluation:
    cmd: python src/train_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_winequality.csv
    - data/processed/test_wine_quality.csv
    - src/train_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - reports/scores.json:
        cache: False
    - reports/params.json:
        cache: False
    outs:
    - saved_models/model.joblib