base:
project: winequality-project
random_state: 42
targe_col: Target


data_source:
  s3_source: data_given/winequality.csv
  
split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_wine_quality.csv
  test_size: 0.25


estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models
